from scavenger import Scavenger
from flickr_scavenger import FlickrScavenger
from github_scavenger import GithubScavenger
from google_plus_scavenger import GooglePlusScavenger
from jigsaw_scavenger import JigsawScavenger
from myspace_scavenger import MyspaceScavenger
from yahoo_scavenger import YahooScavenger
from foursquare_scavenger import FoursquareScavenger
